export const cryptoCurrencies = [
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'MATIC',
    network: 'Polygon',
    address: '0x1e7589c21793286579ffD05E0B5Bcc62A3955fcC',
    coinGeckoId: 'matic-network',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#8247e5',
    mark: '⬡',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    network: 'Ethereum',
    address: '0x1e7589c21793286579ffD05E0B5Bcc62A3955fcC',
    coinGeckoId: 'ethereum',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#627eea',
    mark: '◆',
  },
  {
    id: 'tether',
    name: 'Tether USD',
    symbol: 'USDT',
    network: 'ERC-20',
    address: '0x1e7589c21793286579ffD05E0B5Bcc62A3955fcC',
    coinGeckoId: 'tether',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#26a17b',
    mark: '₮',
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'LTC',
    network: 'Litecoin',
    address: 'LenwzShKjfCHftVty1uFWb4Csc4qkjKSQC',
    coinGeckoId: 'litecoin',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#345d9d',
    mark: 'Ł',
  },
  {
    id: 'bnb',
    name: 'BNB',
    symbol: 'BNB',
    network: 'BNB Smart Chain',
    address: '0x1e7589c21793286579ffD05E0B5Bcc62A3955fcC',
    coinGeckoId: 'binancecoin',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#f3ba2f',
    mark: '◆',
  },
  {
    id: 'usdc',
    name: 'USDC',
    symbol: 'USDC',
    network: 'ERC-20',
    address: '0x1e7589c21793286579ffD05E0B5Bcc62A3955fcC',
    coinGeckoId: 'usd-coin',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#2775ca',
    mark: '$',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    network: 'Solana',
    address: 'yCV7UgU4Vm4i3Uh1Sp6FAsLwUh8cNzp2WWHjDEeSpmw',
    coinGeckoId: 'solana',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#14f195',
    mark: 'S',
  },
  {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    network: 'Tron',
    address: 'TSPAGNJie5qCdAUf1jidgu5YAnPJM6bKxW',
    coinGeckoId: 'tron',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#ff0013',
    mark: '△',
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    network: 'Bitcoin',
    address: 'bc1qndg727ht62smu9v5ftp57t72ssemhqz5pfh84q',
    coinGeckoId: 'bitcoin',
    feeRate: 0.03,
    confirmations: 6,
    accent: '#f7931a',
    mark: '₿',
  },
]

export const fallbackCryptoRatesEur = {
  bitcoin: 98000,
  ethereum: 3200,
  tether: 0.92,
  usdc: 0.92,
  litecoin: 88,
  bnb: 660,
  solana: 145,
  tron: 0.26,
  polygon: 0.22,
}

export function getCryptoById(id) {
  return cryptoCurrencies.find((currency) => currency.id === id) || cryptoCurrencies[0]
}

export function formatCryptoAmount(value, symbol) {
  const decimals = value >= 1 ? 6 : 8
  return `${Number(value).toFixed(decimals).replace(/0+$/, '').replace(/\.$/, '')} ${symbol}`
}
